// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYr4zcL2Q4jWiQeX9lHnSr7VOy4eib16w',
    appId: '1:537016168733:web:e83caa2934b367be1d31f4',
    messagingSenderId: '537016168733',
    projectId: 'jabar-caang-app',
    authDomain: 'jabar-caang-app.firebaseapp.com',
    storageBucket: 'jabar-caang-app.firebasestorage.app',
    measurementId: 'G-XJ63Y7K5LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMZrY15SypCfn5a9Q8t9dn5vv3w9wzhg',
    appId: '1:537016168733:android:5b305c4c174292fa1d31f4',
    messagingSenderId: '537016168733',
    projectId: 'jabar-caang-app',
    storageBucket: 'jabar-caang-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_oqMsWo_aO1jkwYSU4C05esi0UGTKIc',
    appId: '1:537016168733:ios:3542dce90b8c46111d31f4',
    messagingSenderId: '537016168733',
    projectId: 'jabar-caang-app',
    storageBucket: 'jabar-caang-app.firebasestorage.app',
    androidClientId: '537016168733-00qbjp1j6llhcaol47m01cvj9boj2ct1.apps.googleusercontent.com',
    iosClientId: '537016168733-ebi4edtjcbtebo8bn02taeh7hh4lj4d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jabarCaang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd_oqMsWo_aO1jkwYSU4C05esi0UGTKIc',
    appId: '1:537016168733:ios:3542dce90b8c46111d31f4',
    messagingSenderId: '537016168733',
    projectId: 'jabar-caang-app',
    storageBucket: 'jabar-caang-app.firebasestorage.app',
    androidClientId: '537016168733-00qbjp1j6llhcaol47m01cvj9boj2ct1.apps.googleusercontent.com',
    iosClientId: '537016168733-ebi4edtjcbtebo8bn02taeh7hh4lj4d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jabarCaang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYr4zcL2Q4jWiQeX9lHnSr7VOy4eib16w',
    appId: '1:537016168733:web:a502324d6979218b1d31f4',
    messagingSenderId: '537016168733',
    projectId: 'jabar-caang-app',
    authDomain: 'jabar-caang-app.firebaseapp.com',
    storageBucket: 'jabar-caang-app.firebasestorage.app',
    measurementId: 'G-PJ0Q4P9PEV',
  );
}
